### ISSUE TITLE
Internal Server Error 500 (re-issue)

### ISSUE THREAD

**Issue by chicago-joe** [chubin/cheat.sh#423]
Original Issue: **#422** 

I didn't have permissions to re-open it so I had to make a new issue. 

Glanced into the build logs and see:
<img width="647" height="183" alt="Image" src="https://github.com/user-attachments/assets/1c81d7ba-845c-4b94-8e6e-5baa49e5d60e" />

<details>
<summary>
Job Run Snippet Lines 615-758
</summary>

[job log](https://github.com/chubin/cheat.sh/actions/runs/16822510617/job/47652136704#step:615:758)

```
Running 8: :cht.sh
/usr/bin/python3 ../lib/standalone.py :cht.sh
--- results/8^I2025-08-08 05:15:15.525999978 +0000
+++ /tmp/cht.sh.tests-M1VjSQvCA3yaiF^I2025-08-08 05:16:41.971926720 +0000
@@ -114,7 +114,7 @@
     cht.sh --mode lite      # use https://cheat.sh/ only
     cht.sh --mode auto      # use local installation
 
-For intallation and standalone usage, you need \`git\`, \`python\`,
+For installation and standalone usage, you need \`git\`, \`python\`,
 and \`virtualenv\` to be installed locally.
 EOF
     return
@@ -559,7 +559,7 @@
 }
 
 cmd_copy() {
-  if [ -z "$DISPLAY" ]; then
+  if [ -z "$DISPLAY" ] && [ "$is_macos" != yes ]; then
     echo copy: supported only in the Desktop version
   elif [ -z "$input" ]; then
     echo copy: Make at least one query first.
@@ -579,7 +579,7 @@
 }
 
 cmd_ccopy() {
-  if [ -z "$DISPLAY" ]; then
+  if [ -z "$DISPLAY" ] && [ "$is_macos" != yes ]; then
     echo copy: supported only in the Desktop version
   elif [ -z "$input" ]; then
     echo copy: Make at least one query first.
@@ -731,7 +731,7 @@
   curl -s "${CHTSH_URL}"/:cht.sh > "$TMP2"
   if ! cmp "$0" "$TMP2" > /dev/null 2>&1; then
     if grep -q ^__CHTSH_VERSION= "$TMP2"; then
-      # section was vaildated by us already
+      # section was validated by us already
       args=(--shell "$section")
       cp "$TMP2" "$0" && echo "Updated. Restarting..." && rm "$TMP2" && CHEATSH_RESTART=1 exec "$0" "${args[@]}"
     else
FAILED: [8] :cht.sh
Running 9: cht.sh python copy file     # [online]
/usr/bin/python3 ../lib/standalone.py python copy file
--- results/9^I2025-08-08 05:15:15.527000037 +0000
+++ /tmp/cht.sh.tests-M1VjSQvCA3yaiF^I2025-08-08 05:16:42.916926284 +0000
@@ -1,16 +1,23 @@
-^[[38;5;246;03m#  How do I copy a file in Python?^[[39;00m
-^[[38;5;246;03m#  ^[[39;00m
-^[[38;5;246;03m#  shutil (http://docs.python.org/3/library/shutil.html) has many methods^[[39;00m
-^[[38;5;246;03m#  you can use. One of which is:^[[39;00m
-
-^[[38;5;70;01mfrom^[[39;00m^[[38;5;252m ^[[39m^[[38;5;68;04mshutil^[[39;00m^[[38;5;252m ^[[39m^[[38;5;70;01mimport^[[39;00m^[[38;5;252m ^[[39m^[[38;5;252mcopyfile^[[39m
-
-^[[38;5;252mcopyfile^[[39m^[[38;5;252m(^[[39m^[[38;5;252msrc^[[39m^[[38;5;252m,^[[39m^[[38;5;252m ^[[39m^[[38;5;252mdst^[[39m^[[38;5;252m)^[[39m
-
-^[[38;5;246;03m#  Copy the contents of the file named src to a file named dst. The^[[39;00m
-^[[38;5;246;03m#  destination location must be writable; otherwise, an IOError exception^[[39;00m
-^[[38;5;246;03m#  will be raised. If dst already exists, it will be replaced. Special^[[39;00m
-^[[38;5;246;03m#  files such as character or block devices and pipes cannot be copied^[[39;00m
-^[[38;5;246;03m#  with this function. src and dst are path names given as strings.^[[39;00m
-^[[38;5;246;03m#  ^[[39;00m
-^[[38;5;246;03m#  [Swati] [so/q/123198] [cc by-sa 3.0]^[[39;00m
+^[[38;5;248;03m#  [`shutil`][1] has many methods you can use. One of which is:^[[39;00m
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;248;03m#  ```^[[39;00m
+^[[38;5;248;03m#  from shutil import copyfile^[[39;00m
+^[[38;5;248;03m#  copyfile(src, dst)^[[39;00m
+^[[38;5;248;03m#  ```^[[39;00m
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - Copy the contents of the file named **src** to a file named^[[39;00m
+^[[38;5;248;03m#  **dst**.^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - The destination location must be writable; otherwise, an^[[39;00m
+^[[38;5;248;03m#  **IOError** exception will be raised.^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - If **dst** already exists, it will be replaced.^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - Special files such as character or block devices and pipes cannot^[[39;00m
+^[[38;5;248;03m#  be copied with this function.^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - With **copy**, **src** and **dst** are path names given as^[[39;00m
+^[[38;5;248;03m#  __strings__.^[[39;00m
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;248;03m#  If you use `os.path` operations, use `copy` rather than `copyfile`.^[[39;00m
+^[[38;5;248;03m#  `copyfile` will only accept strings.^[[39;00m
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;252m  ^[[39m^[[38;5;248;03m#  [1]: [http://docs.python.org/3/library/shutil.html^[[39;00m](http://docs.python.org/3/library/shutil.html%5E[[39;00m)
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;248;03m#  [Swati] [so/q/123198] [cc by-sa 3.0]^[[39;00m
FAILED: [9] python copy file
Running 10: python/copy+file            # [online]
/usr/bin/python3 ../lib/standalone.py python/copy+file
--- results/10^I2025-08-08 05:15:15.524999919 +0000
+++ /tmp/cht.sh.tests-M1VjSQvCA3yaiF^I2025-08-08 05:16:43.696925653 +0000
@@ -1,16 +1,23 @@
-^[[38;5;246;03m#  How do I copy a file in Python?^[[39;00m
-^[[38;5;246;03m#  ^[[39;00m
-^[[38;5;246;03m#  shutil (http://docs.python.org/3/library/shutil.html) has many methods^[[39;00m
-^[[38;5;246;03m#  you can use. One of which is:^[[39;00m
-
-^[[38;5;70;01mfrom^[[39;00m^[[38;5;252m ^[[39m^[[38;5;68;04mshutil^[[39;00m^[[38;5;252m ^[[39m^[[38;5;70;01mimport^[[39;00m^[[38;5;252m ^[[39m^[[38;5;252mcopyfile^[[39m
-
-^[[38;5;252mcopyfile^[[39m^[[38;5;252m(^[[39m^[[38;5;252msrc^[[39m^[[38;5;252m,^[[39m^[[38;5;252m ^[[39m^[[38;5;252mdst^[[39m^[[38;5;252m)^[[39m
-
-^[[38;5;246;03m#  Copy the contents of the file named src to a file named dst. The^[[39;00m
-^[[38;5;246;03m#  destination location must be writable; otherwise, an IOError exception^[[39;00m
-^[[38;5;246;03m#  will be raised. If dst already exists, it will be replaced. Special^[[39;00m
-^[[38;5;246;03m#  files such as character or block devices and pipes cannot be copied^[[39;00m
-^[[38;5;246;03m#  with this function. src and dst are path names given as strings.^[[39;00m
-^[[38;5;246;03m#  ^[[39;00m
-^[[38;5;246;03m#  [Swati] [so/q/123198] [cc by-sa 3.0]^[[39;00m
+^[[38;5;248;03m#  [`shutil`][1] has many methods you can use. One of which is:^[[39;00m
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;248;03m#  ```^[[39;00m
+^[[38;5;248;03m#  from shutil import copyfile^[[39;00m
+^[[38;5;248;03m#  copyfile(src, dst)^[[39;00m
+^[[38;5;248;03m#  ```^[[39;00m
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - Copy the contents of the file named **src** to a file named^[[39;00m
+^[[38;5;248;03m#  **dst**.^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - The destination location must be writable; otherwise, an^[[39;00m
+^[[38;5;248;03m#  **IOError** exception will be raised.^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - If **dst** already exists, it will be replaced.^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - Special files such as character or block devices and pipes cannot^[[39;00m
+^[[38;5;248;03m#  be copied with this function.^[[39;00m
+^[[38;5;252m ^[[39m^[[38;5;248;03m#  - With **copy**, **src** and **dst** are path names given as^[[39;00m
+^[[38;5;248;03m#  __strings__.^[[39;00m
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;248;03m#  If you use `os.path` operations, use `copy` rather than `copyfile`.^[[39;00m
+^[[38;5;248;03m#  `copyfile` will only accept strings.^[[39;00m
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;252m  ^[[39m^[[38;5;248;03m#  [1]: [http://docs.python.org/3/library/shutil.html^[[39;00m](http://docs.python.org/3/library/shutil.html%5E[[39;00m)
+^[[38;5;248;03m#  ^[[39;00m
+^[[38;5;248;03m#  [Swati] [so/q/123198] [cc by-sa 3.0]^[[39;00m
FAILED: [10] python/copy+file
Running 11: python/copy+file?Q          # [online]
/usr/bin/python3 ../lib/standalone.py python/copy+file?Q
--- results/11^I2025-08-08 05:15:15.524999919 +0000
+++ /tmp/cht.sh.tests-M1VjSQvCA3yaiF^I2025-08-08 05:16:44.458925349 +0000
@@ -1,3 +1 @@
-^[[38;5;70;01mfrom^[[39;00m^[[38;5;252m ^[[39m^[[38;5;68;04mshutil^[[39;00m^[[38;5;252m ^[[39m^[[38;5;70;01mimport^[[39;00m^[[38;5;252m ^[[39m^[[38;5;252mcopyfile^[[39m
 
-^[[38;5;252mcopyfile^[[39m^[[38;5;252m(^[[39m^[[38;5;252msrc^[[39m^[[38;5;252m,^[[39m^[[38;5;252m ^[[39m^[[38;5;252mdst^[[39m^[[38;5;252m)^[[39m
FAILED: [11] python/copy+file?Q
Running 1
```

</details>

**Comment by chicago-joe** [comment]
It seems that some permission / path issues exist during the build and testing stages. 

Furthermore the downstream docker job fails on running to the max execution time of 24 hours. Likely this has something to do with the previous job failures. 

<img width="1291" height="489" alt="Image" src="https://github.com/user-attachments/assets/533373a4-1543-4c99-a4e3-f1eb96823898" />

**Comment by chubin** [comment]
The 'Internal Server Error 500' on the live deployment (https://cheat.sh/) was fixed, please retry

**Comment by LelouBil** [comment]
Not fixed for me

**Comment by chubin** [comment]
Try again

**Comment by LelouBil** [comment]
It works now !

**Comment by Froopity** [comment]
I am still unable to reach https://cheat.sh with the exact same issue.

**Comment by sleepymincy** [comment]
Can confirm, same issue for me.

**Comment by chubin** [comment]
try again

**Comment by sleepymincy** [comment]
> try again

Works now! What's the issue, may I ask? Would be awkward to keep bothering you each time it happens.

**Comment by chubin** [comment]
I've restarted the server. Seems to be a leaked file descriptor.

**Comment by manero6** [comment]
still unreachable with Internal Server Error 500

**Comment by chubin** [comment]
Try again

**Comment by manero6** [comment]
@chubin nice, it works now!

**Comment by mre** [comment]
Looks like it's down again. Getting a 500.

**Comment by chubin** [comment]
Please retry

**Comment by mre** [comment]
It's up, thanks!

**Comment by abitrolly** [comment]
Maybe setup automated alerting? Not sure if there any bots on GitHub Marketplace.

**Comment by chubin** [comment]
Better fix it properly instead, and that's exactly what I am going to do

**Comment by andylin2004** [comment]
Attempting to use cheat.sh today and it still gives me a 500 error

**Comment by chubin** [comment]
Please retry

**Comment by andylin2004** [comment]
Perfect. Seems like it’s working again.On Oct 7, 2025, at 3:02 PM, Igor Chubin ***@***.***> wrote:﻿chubin left a comment (chubin/cheat.sh#423)
Please retry

**Comment by psychananaz** [comment]
It's down again. Has been for ages with a few openings occasionally.

**Comment by chubin** [comment]
Please try again now.

I am working on a new version (a complete rework from scratch) where the problem does not exist

**Comment by morindo** [comment]
Attempting to use cheat.sh today and it still gives me a 500 error

**Comment by chubin** [comment]
Not still, but again. Please retry now

**Comment by HumbleGrumble87** [comment]
Down again! Thank you for maintaining this - saves my life every other day :)

**Comment by chubin** [comment]
Please retry

**Comment by HumbleGrumble87** [comment]
ferris bueller you're my hero

Sent from [Proton Mail](https://proton.me/mail/home) for Android.

-------- Original Message --------

**Comment by clementgineste** [comment]
Same for me here

**Comment by chubin** [comment]
Please try again

**Comment by darkgeem** [comment]
Still(again?) down for me =w="

**Comment by chubin** [comment]
Please try again

**Comment by caner-cetin** [comment]
well... its down again.

**Comment by chubin** [comment]
Please try again

**Comment by caner-cetin** [comment]
and its up!

**Comment by falcon217836** [comment]
Down again this afternoon.

**Comment by chubin** [comment]
up again

**Comment by clementgineste** [comment]
Need help hosting ? :D

**Comment by mcint** [comment]
Down again, entirely offline yesterday and today.

With some cache headers on the responses, and a CDN in front, this could handle the traffic.

_Help us help you, thanks for providing fantastic cli services—your work is an inspiration!_

**Comment by chubin** [comment]
Is it really down? It seems to work and the logs are fine too... Please could you verify it again?

**Comment by mcint** [comment]
I was getting, not even 500s, but connection timeouts.

Today now, everything is fast and smooth (rate.sx, wttr.in, cht.sh). Thank you for hosting!

**Comment by nicomda** [comment]
Down!

**Comment by chubin** [comment]
Up

**Comment by vaibhav423** [comment]
Down

**Comment by vaibhav423** [comment]
any recommended alternatives to try when down

**Comment by chubin** [comment]
Up; no alternatives from my side, but there is a hope that it will be fixed soon

**Comment by OnlyXuul** [comment]
Seems to be down again. Please tell me this is still maintained. I love using cheat. :)

**Comment by chubin** [comment]
Please retry

**Comment by OnlyXuul** [comment]
Woot! That's better.

**Comment by justin13888** [comment]
Down again (and I'm not on VPN)

**Comment by chubin** [comment]
Retry

**Comment by BasixKOR** [comment]
seems to be down again :(

**Comment by chubin** [comment]
Up again. Sorry for the inconvenience, after switch to the new engine the problem will disappear.

**Comment by solt87** [comment]
And yet again, there is the internal server error (500).

**Comment by chubin** [comment]
@solt87 Please try again

**Comment by lehlud** [comment]
worked for a while (a few hours ago, it worked for me); now the http 500 is back

**Comment by chubin** [comment]
@lehlud please try again

**Comment by lehlud** [comment]
@chubin works now. Is this temporary or is it assumed to be a recurring problem in the future?

**Comment by dot-mike** [comment]
500 error is back...

**Comment by chubin** [comment]
try again

**Comment by zub-bee** [comment]
@chubin hi

Just discovered cheat.sh, and it's down with an Internal Server Error.

**Comment by chubin** [comment]
retry
